### ISSUE TITLE
Subject:The Urnetians lor

### ISSUE THREAD

**Issue by AngelOfDarkess** [anthonysSlab/AshenOdyssey#4]
The Urnetians are a species of sentient ursines, most resembling what would be best described as pandas in human terms. They inhabit the constellation designated by the empire Aner-3r, which consists of six planets and an artificially created star. Curiously, this star serves as a defense system for the Urnetians due to its heat, which is four times that of Earth's sun. As a result, invading the Urnetian planet is only possible once every seven years when the star cools itself down.

The Urnetians, aware of this fact, make preparations for invasion every seven years. They reside on a moon three times the size of Earth's moon. This moon's rotation around the planet enables the Urnetians to survive the extreme temperatures by avoiding the sun's intense radiation and maintaining an unnatural biosphere. Remarkably, they possess complete control over their moon using biotechnology, which the empire struggles greatly to obtain.

Interestingly, any piece of biotech taken from Aner-3r by the empire simply decays once it leaves the planet, rendering it unusable and preventing scientific research.

Contrary to most species, the Urnetians adhere to a single belief and religious system, with slight variations among individuals. However, what strikes observers as intriguing is their striking resemblance to Chinese culture. Their way of life emphasizes a deep connection with nature and a harmonious existence, leading to the theory that their technological development has played a significant role in shaping their cultural practices.

In terms of biology, the Urnetians exhibit remarkable similarities to humans. They share many physiological features and functions, making them relatable in various ways. Despite being omnivores, their diet primarily consists of plants and insects. While they are capable of consuming meat, the Urnetians prefer to include insects in their diet, allowing for a more balanced and sustainable way of life.

One notable aspect of their biology is their extraordinarily strong sense of smell, akin to that of a wolf. Their olfactory capabilities surpass those of humans, enabling them to detect scents with remarkable precision and detail. Additionally, the Urnetians possess acute hearing, further contributing to their sensory prowess. Their keen sense of hearing allows them to perceive sounds that might go unnoticed by other species, enhancing their awareness of their surroundings.

Overall, the Urnetians' biological characteristics, including their preference for a plant-based and insect-rich diet, their heightened sense of smell, and their acute hearing, all contribute to their unique adaptation and interaction with their environment.

The origins of Urnetian technology remain a mystery, as it is unclear how it was discovered or created. The Urnetians themselves hold a belief that their technological advancements were bestowed upon them by an ancient alien species. According to their religious beliefs, this enigmatic and revered species played a crucial role in catalyzing the Urnetians' evolution and development.

In Urnetian mythology and spirituality, their central religious figure is depicted as a humanoid creature with a faceless visage and multiple arms. This figure represents the connection between the Urnetians and the ancient alien species they revere. The belief is that this benevolent entity, with its otherworldly wisdom and capabilities, guided the Urnetians towards the path of technological progress and enlightenment.

While the exact nature and intentions of this ancient alien species remain a subject of speculation and reverence, the Urnetians attribute their advancements to the influence and assistance of these mysterious beings. It is through this belief that they find purpose and meaning in their technological achievements, considering themselves the beneficiaries of a profound cosmic heritage.

**Comment by slbsh** [comment]
same as #5
