### ISSUE TITLE
Subject: New species request, with lor and physical attributes.

### ISSUE THREAD

**Issue by AngelOfDarkess** [anthonysSlab/AshenOdyssey#5]
Public Statement: The Primorths of Xalos VII

To the General Public,

We are pleased to share with you valuable information about the extraordinary species known as the Primorths, originating from the hostile planet of Xalos VII. Their unique attributes and remarkable achievements have captivated the attention of interstellar communities, making them an intriguing subject of study and admiration.

The Primorths possess an impressive set of physical characteristics that make them a force to be reckoned with. As sentient, carnivorous primates, they boast an outer shell of bone, providing them with natural armor that renders them impervious to most conventional attacks. With razor-sharp teeth and claws, they possess deadly weapons capable of swiftly incapacitating prey or defending themselves against potential threats.

One distinctive aspect of the Primorths' sensory perception is their full colorblindness, allowing them to perceive their surroundings solely in shades of black and white. Nevertheless, they compensate for this limitation with a heightened sense of smell and acute hearing, enabling them to navigate their hostile environment and detect dangers effectively.

The Primorths' triumph lies not only in their physical attributes but also in their impressive technological advancements. Despite the unforgiving nature of Xalos VII, they have managed to develop a highly advanced civilization by harnessing the planet's resources ingeniously. From energy sources to the construction of intricate city structures, their accomplishments serve as a testament to their unwavering determination and exceptional adaptability.

Their regenerative abilities are extraordinary. While most of their body parts can regenerate within a day, such as limbs, their core, vaguely resembling a heart, is heavily protected by their biological bone armor. Regenerating the core can take months, even with the assistance of medical professionals or advanced technology. This vulnerability underscores the importance of safeguarding their core, as its loss could have severe consequences for their survival.

Furthermore, it is important to note that the Primorths are proud members of the Federation, an interstellar organization dedicated to fostering peace, cooperation, and mutual understanding among diverse species. Their affiliation signifies their commitment to interstellar diplomacy and their desire to contribute to the harmony of the cosmos.

While the Primorths possess formidable predatory instincts, their civilization is widely regarded as peaceful. The devastating consequences of past conflicts within their society nearly wiped them out of existence, leading them to recognize the sickening nature of warfare. As a result, they have embraced pacifism and prioritize peaceful resolutions over aggression. Their forms of warfare, when employed, are considered abhorrent even by human standards.

Empathy and the ability to understand others, both within their species and among alien civilizations, hold great value for the Primorths. They view empathy as a virtue and strive to foster understanding and harmony among diverse beings. However, it is essential to note that the Primorths possess a strong sense of justice and will not hesitate to respond decisively if they are attacked or faced with defiance. In such cases, the offending civilization may face severe consequences, potentially leading to extermination.

While the Primorths maintain their distance from the empire, their clear and unmistakable disdain for the empire's methods and ideologies is evident. While they may not oppose the empire directly, their distaste and disapproval are palpable, reflecting their commitment to their own principles and their desire to preserve their autonomy.

In conclusion, the Primorths of Xalos VII embody the incredible potential of intelligent life in the face of adversity. Their lethal physical attributes, technological prowess, and conquest of their hostile home planet and star system inspire awe and admiration. As we continue to study and engage with this remarkable species, let us approach them with respect, curiosity, and a desire for peaceful cooperation, while recognizing their regenerative abilities, vulnerability in their core, commitment to peace, and empathy.

-

Physical Description: The Primorths of Xalos VII

The Primorths of Xalos VII possess a distinctive and formidable physical appearance, reflecting their adaptation to the hostile environment of their home planet. Here are some key details about their visual characteristics:

- Outer Armour: The Primorths boast an impressive outer shell made of bone, which acts as natural armor, providing them with exceptional protection against external threats. This bone armor is flexible, allowing for ease of movement despite its sturdy nature.

- Colouration: The Primorths' armor is typically observed in shades of brown, black, grey, or white, blending seamlessly with their environment. Additionally, their skin tone ranges from grey to white, providing camouflage in their natural habitat.

- Eyes: Their eyes are predominantly black or dark brown, enhancing their visual acuity in low-light conditions and aiding their predatory instincts.

- Teeth and Claws: The Primorths possess both exterior and interior razor-sharp teeth, optimized for tearing through flesh and consuming their prey. Additionally, their claws are formidable weapons, enabling them to grasp and subdue adversaries with precision and strength.

- Tails: They possess tails, typically measuring around 30 centimeters in length, aiding in balance and agility during movement.

- Height: The average height of a Primorth ranges from 1.80 to 2.00 meters, comparable to the stature of an average human. However, their physical builds can vary depending on factors such as weight, body type, and individual variations.

- Hair: Primorths commonly display head hair in shades of grey, black, brown, or white, adding to the diversity of their appearance. Notably, they do not possess facial hair.

Overall, the Primorths' physical features, such as their bone armor, sharp teeth and claws, tails, and impressive stature, reflect their evolutionary adaptation to their hostile home planet. These characteristics, combined with their advanced technology and pacifist nature, make them a remarkable and intriguing species worthy of study and respect.

**Comment by slbsh** [comment]
Please limit the verbocity of issues, and only add large swaths of text within PR's

Quick bullet points are preffered

also: as a Contributor you are able to directly Commit to the main branch, please do so whenever this gets approved
