### ISSUE TITLE
More complex combat mechanics.

### ISSUE THREAD

**Issue by AngelOfDarkess** [anthonysSlab/AshenOdyssey#6]
Here's a modified version that adds complexity to the player combat/death aspect while keeping the rest of the combat system simplified:

1. Attack Rolls:
   - Roll a d20 to make an attack.
   - Add a modifier based on the character's weapon, skill, or situational advantage.

2. Defense Rolls:
   - Roll a d20 to defend against attacks.
   - Add a modifier based on the character's agility, armor, or situational advantage.

3. Damage Resolution:
   - If the attack roll is higher than the defense roll, the defender takes a hit.
   - No damage calculations are made; it's a binary hit or miss.

4. Player Death:
   - When a player character is hit, player rolls a d20 to determine the severity of the injury.
   - Add Skill to the roll d20 roll.
   - The DC is determined by the DM 
   - Depending on the roll, various outcomes can occur, ranging from minor wounds to fatal injuries.
   - The severity can be influenced by factors such as the attacker's strength or critical hits.

5. Death Outcomes:
   - Roll a d6 to determine the outcome of a fatal injury:
     •1. Death: The character dies immediately.
     •2. Critical Condition: The character is on the brink of death and requires immediate medical attention.
     •3. Permanent Injury: The character survives but suffers a lasting physical or mental impairment.
     •4. Near-Death Experience: The character is unconscious but can be conscious with timely intervention.
     •5. Miraculous Recovery: Against all odds, the character survives with minimal consequences.
     •6. Last Stand: The character makes a final heroic effort before getting injured, and suffer minimal consequences.

 [Luck can be used to reroll D6 at ADV / DDV] 

6. Revival and Recovery:
   - Characters in critical condition can be revived through timely medical treatment. 
   - Permanent injuries may require specialized treatment for partial or full recovery.

**Comment by slbsh** [comment]
this would go fully against the core pillar of "npc's never roll"; 
please update this suggestion, while keeping that in mind.

Ideally we'd want the players rolling both for their attack, and their defence.

as for the damage severity, I like it, just one thing:
we prob dont want any positives coming from it, keep something along the lines of "minor scratches and bruises" as the best, and "instant and gory death" as the worst.

also luck can already influence death :L
